### ISSUE TITLE
Incomplete list of centralities 

### ISSUE THREAD

**Issue by MustafaMustafa** [GuannanXie/Run14AuAu200GeV_StRefMultCorr#1]
Hello @GuannanXie, 

Please add to your header files the case -1. For example:
https://github.com/GuannanXie/Run14AuAu200GeV_StRefMultCorr/blob/master/VPDMB5/StRefMultCorr/StRefMultCorr.h#L37

**Comment by GuannanXie** [comment]
Done, thanks.
